config/routes.rb
Rails.application.routes.draw do

  root 'static_page#home'
  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/auth/facebook/callback' => 'session#create'
  get '/logout' => 'session#destroy'

  resources :tasks, only: [:create, :destroy, :edit, :update] do 
    resources :users, only: [:show]
  end 

  resources :lists, only: [:index, :show, :create, :update, :destroy, :new] do
    resources :tasks, only: [:new, :show, :edit, :update, :destroy]
  end 

  resources :users, only: [:create, :destroy, :edit, :update, :show] do
    resources :lists, only: [:new, :edit, :show, :update, :destroy]
  end
  
  resources :users do 
    resources :tasks, only: [:show, :edit]
  end 

  resources :users_tasks
  
end

app/models/list.rb
class List < ApplicationRecord
    validates :title, presence: true

    has_many :tasks 
    belongs_to :user
    
    def list_complete?
        !tasks.any?{|task| task.status == "Incomplete"}
    end 
 
 
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

    def index
        @lists = List.all
        respond_to do |format|
            format.html {render :index}
            format.json {render json: @lists}
          end
    end  

    def new
        @list = List.new(user_id: current_user.id)
        
    end 

    def create 
        @list = List.create(list_params)
        if @list.save
            respond_to do |format|
                format.html {redirect_to user_list_path(current_user, @list)}
                format.json {render json: @list}
              end
        else
            render 'new'
        end 
    end 

    def show
        @list = List.find_by(id: params[:id])
        respond_to do |format|
            format.html {render :show}
            format.json {render json: @list}
          end
    end 

    def edit
        @list = List.find_by(id: params[:id])
    end 

    def update 
        @list = List.find_by(id: params[:id])
    
        if @list.update(list_params)
            respond_to do |format|
                format.html {redirect_to list_path(@list)}
                format.json {render json: @list}
              end
        else 
            render 'edit'
        end 
    end 

    def destroy 
        list = List.find_by(id: params[:id])
        list.destroy
        redirect_to user_path(current_user)
    end 

    private 

    def list_params
        params.require(:list).permit(:title, :user_id)
    end 
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>

    <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2 class="text-danger">
        <%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:
      </h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>


  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.hidden_field :user_id %>

  <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/lists/edit.html.erb
<h1>Edit Your List Title</h1>

<%= render 'form' %>

app/views/lists/index.html.erb
<div>
    <table class="table">
    <tbody>
        <tr>
            <th>Lists</th>
            <th>Complete/Incomplete</th>
            <th>Expand List</th>
        </tr>
        <% @lists.each do |list| %>
            <tr>
                <td><%= list.title %></td>
            <% if list.list_complete? %>
                <td class="text-success">Complete</td>
            <% else %>
                <td class="text-danger">Incomplete</td>
            <% end %>
            <td><%= link_to "Expand", list_path(list) %></td>
        <% end %>
        </tr>
    </tbody>
    </table>
    
    <p><%= link_to "Create a List", new_user_list_path(current_user) %></p>
</div>

app/views/lists/new.html.erb
<div id="new_list_container">
    <h1>Create A List</h1>

    <%= render 'form' %>
</div>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>

<h5 class="text-secondary">Created by: <%= link_to @list.user.name, user_path(@list.user) %> </h5>

<% if current_user.lists.include?(@list) %>
    <p><%= link_to "Change Title", edit_user_list_path(@list) %></p>
    
    <p><%= link_to "Add a Task", new_list_task_path(@list) %></p>

<% end %>

<div>
    <table class="table">
    <tbody>
        <tr>
            <th>Task</th>
            <th>Complete/Incomplete</th>
            <th>Checkout Task</th>
        </tr>

        <% @list.tasks.each do |task| %>
        <tr>
            <td><%= task.title %></td>
            <% if task.completed %>
            <td class="text-success"><%= task.status %></td>
            <% else %>
            <td class="text-danger"><%= task.status %></td>
            <% end %>
            <td><%= link_to "Checkout", list_task_path(@list, task) %></td>

        <% end %>
        </tr>

    </tbody>
    </table>

    <% if current_user.lists.include?(@list) %>
        <p>
            <%= form_for @list, method: :delete do |f| %>
                <%= f.submit "Delete List", class: "text-danger" %>
            <% end %>
        </p>
        
<% end %>
</div>