config/routes.rb
Rails.application.routes.draw do

  root 'static_page#home'
  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/auth/facebook/callback' => 'session#create'
  get '/logout' => 'session#destroy'

  resources :tasks, only: [:create, :destroy, :edit, :update] do 
    resources :users, only: [:show]
  end 

  resources :lists, only: [:index, :show, :create, :update, :destroy, :new] do
    resources :tasks, only: [:new, :show, :edit, :update, :destroy]
  end 

  resources :users, only: [:create, :destroy, :edit, :update, :show] do
    resources :lists, only: [:new, :edit, :show, :update, :destroy]
  end
  
  resources :users do 
    resources :tasks, only: [:show, :edit]
  end 

  resources :users_tasks
  
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  skip_before_action :verify_user_is_authenticated, only: [:home]
  def home
    
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/static_page/home.html.erb
<div>
    <% if current_user %>
        <h1>Hello <%= current_user.name %>!</h1>
    <div>
    <table class="table">
        <tbody>
            <tr>
                <th>Title</th>
                <th>Complete/Incomplete</th>
                <th>Accepeted/Unaccepted</th>
                <th>Checkout Task</th>
            </tr>
            <% current_user.tasks.each do |task| %>
                <tr>
                    <td><%= task.title %></td>

                    <% if task.completed %>
                    <td class="text-success"><%= task.status %></td>
                    <% else %>
                    <td class="text-danger"><%= task.status %></td>
                    <% end %>

                    <% if task.user_accepted?(current_user) %>
                    <td class="text-success">Accepted</td>
                    <% else %>
                    <td class="text-warning">Unaccepted</td>
                    <% end %>

                    <td><%= link_to "Checkout", user_task_path(current_user, task) %></td>
            <% end %>
            </tr>
        </tbody>
    </table>
    </div>

    <div id="list-button">
        <button class="btn-info" id="show-lists">Show Lists</button>
    </div>
    <ol id="lists">
    </ol>
    
    
    <% else %>
        <div>    
            <h1>Welcome to Task Manager!</h1>
            
            <p class="text-secondary">We are here to help you organize your work-life.</p>
            
            <p class="text-secondary">Please signup or login below... </p>
        </div>
            <p><%= link_to "Sign Up", signup_path %></p>
            <p><%= link_to "Log In", login_path %></p>
            <p><%= link_to('Log in with Facebook!', '/auth/facebook') %></p>
    <% end %>
</div>