config/routes.rb
Rails.application.routes.draw do

  root 'static_page#home'
  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/auth/facebook/callback' => 'session#create'
  get '/logout' => 'session#destroy'

  resources :tasks, only: [:create, :destroy, :edit, :update] do 
    resources :users, only: [:show]
  end 

  resources :lists, only: [:index, :show, :create, :update, :destroy, :new] do
    resources :tasks, only: [:new, :show, :edit, :update, :destroy]
  end 

  resources :users, only: [:create, :destroy, :edit, :update, :show] do
    resources :lists, only: [:new, :edit, :show, :update, :destroy]
  end
  
  resources :users do 
    resources :tasks, only: [:show, :edit]
  end 

  resources :users_tasks
  
end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true

    has_many :users_task
    has_many :users, through: :users_task
    belongs_to :list

    def status
        completed ? "Complete" : "Incomplete"
    end 

    def user_accepted?(user)
        users_task.find{|user_task|user_task.user_id == user.id}.accepted
    end 

    def unaccepted_users
        users.select do |user|
            user_accepted?(user) == false
        end 
    end 
    
    def completed_label
        completed ?  "Completed" : "Update Status"
    end 

    def completed_klass
        completed ?  "text-success" : "text-danger"
    end 
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    def new
        @task = Task.new(list_id: params[:list_id])
    end 

    def create 
        @task = Task.create(task_params)
        if @task.save
            respond_to do |format|
                format.html {redirect_to list_task_path(@task.list, @task)}
                format.json {render json: @task}
            end
        else
            render 'new' 
        end
    end 

    def show
        @task = Task.find_by(id: params[:id])
        @user_task = @task.users_task.find{|user_task|user_task.user_id == current_user.id}
        respond_to do |format|
            format.html {render :show}
            format.json {render json: @task}
          end
    end 

    def edit 
        @task = Task.find_by(id: params[:id])
        respond_to do |format|
            format.html {render :edit}
            format.json {render json: @task}
          end
    end 

    def update
        @task = Task.find_by(id: params[:id])
        if @task.update(task_params)
            respond_to do |format|
                format.html {redirect_to list_task_path(@task.list, @task)}
                format.json {render json: @task}
              end
        else 
            render 'edit'
        end 
    end

    def destroy 
        task = Task.find_by(id: params[:id])
        @list = task.list
        task.destroy
        redirect_to list_path(@list)
    end 

    private 

    def task_params
        params.require(:task).permit(:title, :note, :list_id, :completed, user_ids: [])
    end 
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>   

    <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2 class="text-danger">
        <%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:
      </h2>

      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :note %>
  <%= f.text_field :note %>

  <%= f.hidden_field :list_id %>

  <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Your Task</h1>

<%= render 'form' %>

app/views/tasks/new.html.erb
<h1>Create a Task for your List</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm">
            <h1><%= @task.title %></h1>
            <% if @task.completed %>
                <p class="text-info"><span class="border border-success">Note: <%= @task.note %></span></p>
            <% else %>
                <p class="text-info"><span class="border border-danger">Note: <%= @task.note %></span></p>
            <% end %>
            <p class="text-secondary">Return to list: <%= link_to @task.list.title, list_path(@task.list) %></p>
            <% if !@task.completed %>
                <p class="text-info"><span class="text-danger">Status: <%= @task.status %></span></p>
            <% end %>
            <% if @task.list.user == current_user %>
            <%= form_for(@task, url: {controller: 'tasks', action: 'update'}) do |f| %>
                
                <% if @task.completed %>
                <%= f.hidden_field :completed, value: false  %>
                <% else %>
                <%= f.hidden_field :completed, value: true %>
                <% end %>
                
                <%= f.submit @task.completed_label, class: @task.completed_klass %>

            <% end %>

            <p>
                <%= form_for @task, method: :delete do |f|%>
                    <%= f.submit "Delete Task", class: "text-danger" %>
                <% end %>
            </p>
        <% end %> 

        </div>
        <div class="col-sm">
            <% if current_user.list_tasks(@task.list).include?(@task) %>
                <p><%= link_to "Edit Task", edit_user_task_path(@task) %></p>
                <p><b>Assign a User to this Task:</b></p>

                <%= form_for @task, url: {controller: 'tasks', action: 'update'} do |f|%>
                    <%= collection_check_boxes(:task, :user_ids, User.all, :id, :name) %>
                    <br>
                    <%= f.submit "Update Assignments" %>
                <% end %>
            <% end %>
        <div class="p-3">
            <p><b>Users Assigned to Task:</b></p>

            <% if @task.users %>
                <ul>
                <% @task.users.each do |user| %>
                    <li>
                        <b>|</b><%= link_to user.name, user_path(user) %><b>|</b>
                        <br>
                        <% if user == current_user && !@user_task.accepted %>
                        
                        <%= form_for(@user_task, url: users_task_path(@user_task), method: :patch) do |f| %>

                            <%= f.hidden_field :accepted, value: true %>
                            <%= f.submit "Accept Task", class: 'text-warning' %>
                        
                        <% end %>
                        <% elsif @task.unaccepted_users.include?(user) %>
                            <span class="text-warning">Unaccepted</span>
                  
                        <% end %>
                    </li>
                <% end %>
                </ul>
            <% end %>
        </div>
        </div>
    </div>
</div>