config/routes.rb
Rails.application.routes.draw do

  root 'static_page#home'
  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/auth/facebook/callback' => 'session#create'
  get '/logout' => 'session#destroy'

  resources :tasks, only: [:create, :destroy, :edit, :update] do 
    resources :users, only: [:show]
  end 

  resources :lists, only: [:index, :show, :create, :update, :destroy, :new] do
    resources :tasks, only: [:new, :show, :edit, :update, :destroy]
  end 

  resources :users, only: [:create, :destroy, :edit, :update, :show] do
    resources :lists, only: [:new, :edit, :show, :update, :destroy]
  end
  
  resources :users do 
    resources :tasks, only: [:show, :edit]
  end 

  resources :users_tasks
  
end

app/models/user.rb
class User < ApplicationRecord
    validates :password, confirmation: true
    validates :name, presence: true 
    validates :email, presence: true 
    validates :email, uniqueness: true


    has_secure_password 

    has_many :lists
    has_many :users_task
    has_many :tasks, through: :users_task

    def self.find_or_create_by_omniauth(auth_hash)
        where(email: auth_hash["info"]["email"]).first_or_create do |user|
            user.password = SecureRandom.hex 
            user.name = auth_hash["info"]["name"]
        end  
    end

    def list_tasks(user_list)
        if lists.include?(user_list)
            user_list.tasks 
        else
            []
        end 
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :verify_user_is_authenticated, only: [:new,:create] 
    
    def new 
        @user = User.new
    end 

    def create
        @user = User.create(user_params)

        if @user.save
            session[:user_id] = @user.id 
            session_login(@user)
        else
            render 'new'
        end 
    end 

    def show
        @user = User.find_by_id(params[:id])
        @unaccepted_user_tasks = UsersTask.unaccepted_by_user(@user)
        respond_to do |format|
            format.html {render :show}
            format.json {render json: @user}
          end
    end

    def edit 
        @user = User.find_by_id(params[:id])
        respond_to do |format|
            format.html {render :edit}
            format.json {render json: @user}
          end
        
    end 
    
    def update
        @user = User.find_by(id: params[:id])
        if @user.update(user_params)
            respond_to do |format|
                format.html {redirect_to user_path(@user)}
                format.json {render json: @user}
            end
        else 
            render 'edit'
        end 
    end

    private 

    def user_params 
        params.require(:user).permit(:name, :email, :password, :password_confirmation, task_ids: [])
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

    <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2 class="text-danger">
        <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
      </h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
        
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>

  <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/users/edit.html.erb
<h1>Update Your Account with Task Manager!</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Create an Account with Task Manager!</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div>
    <div>
    <% if current_user == @user %> 
        <% unless @unaccepted_user_tasks.empty? %>
            <p class="text-warning"><b>ATTENTION NEEDED, please accept assigned tasks:</b></p>
                <table class="table">
                <tbody>
                <tr>
                    <th>Tasks</th>
                    <th>Accept</th>
                </tr>
                <% @unaccepted_user_tasks.each do |user_task| %>
                    <tr>
                        <td><%= link_to user_task.task.title, user_task_path(user_task.user, user_task.task) %></td>
                        <td>
                        <%= form_for(user_task, url: users_task_path(user_task), method: :patch) do |f| %>

                            <%= f.hidden_field :accepted, value: true %>
                            <%= f.submit "Accept Task" %>
                        <% end %>
                        </td>
                    </tr>
                <% end %>
                </tbody>
                </table>
        <% end %>
    </div>
</div>

<div>
        <h1><%= @user.name %></h1>
        <p><%= link_to "Edit Info", edit_user_path(@user) %></p>
        <h2 class="text-secondary">Your Lists:</h2>
    <% else %>
        <h1><%= @user.name %>'s Page</h1>
        <h2 class="text-secondary">Their Lists:</h2>
    <% end %>
    <div>
        <table class="table">
            <tbody>
                <tr>
                    <th>Title</th>
                    <th>Complete/Incomplete</th>
                    <th>Expand List</th>
                </tr>
                <% @user.lists.each do |list| %>
                    <tr>
                        <td><%= list.title %></td>
                    <% if list.list_complete? %>
                        <td class="text-success">Complete</td>
                    <% else %>
                        <td class="text-danger">Incomplete</td>
                    <% end %>
                    <td><%= link_to "Expand", user_list_path(@user, list) %></td>
                <% end %>
                </tr>
            </tbody>
        </table>
        <% if current_user == @user %>
            <p><%= link_to "New List", new_user_list_path(@user) %></p>
        <% end %>
    </div>

    <div>
    <% if current_user == @user %>
        <h2 class="text-secondary">Your Tasks:</h2>
        <% else %>
        <h2 class="text-secondary">Their Tasks:</h2>
    <% end %>
        <table class="table">
        
        <table class="table">
        <tbody>
            <tr>
                <th>Title</th>
                <th>Complete/Incomplete</th>
                <th>Accepted/Unaccepted</th>
                <th>Checkout Task</th>
            </tr>
            <% @user.tasks.each do |task| %>
                <tr>
                    <td><%= task.title %></td>
                    <% if task.completed %>
                    <td class="text-success"><%= task.status %></td>
                    <% else %>
                    <td class="text-danger"><%= task.status %></td>
                    <% end %>

                    <% if task.user_accepted?(@user) %>
                    <td class="text-success">Accepted</td>
                    <% else %>
                    <td class="text-warning">Unaccepted</td>
                    <% end %>
                    <td><%= link_to "Checkout", user_task_path(@user, task) %></td>
            <% end %>
            </tr>
        </tbody>
        </table>
    </div>
</div>